version: '2.1'

volumes:
   geoserver-data:
   geo-db-data:

services:
   db:
      image: kartoza/postgis:13.0
      network_mode: host
      volumes:
         - geo-db-data:/var/lib/postgresql
      healthcheck:
         test: "exit 0"
      ports:
         - "25434:5432"
   geoserver:
      image: kartoza/geoserver:2.19.0
      network_mode: host
      volumes:
         - geoserver-data:/opt/geoserver/data_dir
      ports:
         - "8600:8080"
      depends_on:
         db:
            condition: service_healthy
