Este documento descreve a utilização dos arquivos contidos neste
repositório, responsáveis pela orquestração dos serviços PostGIS e GeoServer.

* Instalação

  1. Clonamos este repositório, isto é, fazemos uma cópia local dele
     em nosso computador.
     #+begin_src sh
     git clone https://github.com/WebSIG-Ambiental-CFMA/docker-geoserver-postgis
     #+end_src
  2. Entramos no diretório criado pelo comando anterior.
     #+begin_src sh
     cd docker-geoserver-postgis
     #+end_src
  3. "Levantamos" nossos serviços.
     #+begin_src sh
     docker-compose up
     #+end_src
     Destacamos que esse comando é suficiente para o download,
     configuração e inicialização de nossos serviços, de forma a
     promover a integração entre os serviços.

     Notamos também que alguns diretórios serão criados. Tais
     diretórios são chamados *volumes*, e representam o conteúdo de
     certos diretórios dos containers em nosso sistema de arquivos
     local.

* Execuções Posteriores

  Para a inicialização de nossos serviços após a instalação, basta
  seguir os passos 2 e 3 da seção de instalação.
