* Pasta sql_scripts
  Contém arquivos com scripts sql. É esperado que o arquivo
  ~tabela.sql~ contenha os comandos sql necessários para criar uma
  tabela chamada ~tabela~. Preferencialmente, o conteúdo de
  ~tabela.sql~ deve ser apenas uma instrução sql da forma ~CREATE
  TABLE IF NOT EXISTS~.
* Pacote utils
  Contém módulos descrevendo classes para realizar a comunicação com
  os servidores PostGIS e GeoServer. Além disso, há um módulo com uma
  classe gerenciadora que integra a comnnicação com ambos os
  servidores.
* Arquivo Dockerfile
  Define o processo de criação de uma imagem contendo o serviço de inicialização.
* Arquivo requirements.txt
  Lista as bibliotecas python utilizadas no sistema de
  inicialização. Esse arquivo é utilizado principalmente pelo
  Dockerfile, para a correta construção da imagem desse serviço.
* main.py
  Responsável por carregar os módulos do pacote utils, assim como ler
  as variáveis de ambiente, que devem ser determinadas pelo arquivo
  .env, um diretório acima deste. Estabelece conexões com os
  servidores PostGIS e GeoServer, para em seguida construir o
  gerenciador de inicialização com tais conexões. Por fim, o
  gerenciador de inicialização faz a integração inicial dos servidores
  e executa cada script sql na pasta de scripts, por padrão
  ~sql_scripts~.
